name: docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        export CONDA_URL=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
        wget CONDA_URL | 
            bash -s -- --batch
        conda install -c conda-forge mamba
        mamba env create -f env-dev.yml
        conda run --name aizynth-dev poetry install -E all
        conda run --name aizynth-dev inv build-docs
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        publish_branch: gh-pages
        force_orphan: true
